name: C/C++ CI

on:
  push:
    branches: [ master, CI_action ]
  pull_request:
    branches: [ master, CI_action ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: to_carts_repo
      run: cd ../../
    - name: make_objects
      run: make ./bin/objects.a
