name: C/C++ CI

on:
  push:
    branches: [ master, CI_action ]
  pull_request:
    branches: [ master, CI_action ]

jobs:
  build:

    runs-on: ubuntu-latest
  - name: Set up Clang
    uses: egor-tensin/setup-clang@v1
    with:
      version: latest
      platform: x64

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make ./bin/objects.a
