name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: to_carts_repo
      run: cd ../../
    - name: make_objects
      run: make ./bin/objects.a
    - name: add
      run: git add ./bin/objects.a
    - name: commit
      run: git commit -m "executable"
